name: CI Pipeline
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js (or another language, e.g., Python, .NET)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or use .NET SDK or Java, etc.

      - name: Install dependencies
        run: npm install  # Change to dotnet restore for .NET apps

      - name: Run tests
        run: npm test  # Change to dotnet test for .NET apps

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results/*.xml
